version: '3.8'

services:
  backend1:
    build: ./backend
    ports:
      - "4001:4000"
    environment:
      - SESSION_SECRET=your-very-strong-secret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  backend2:
    build: ./backend
    ports:
      - "4002:4000"
    environment:
      - SESSION_SECRET=your-very-strong-secret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  backend3:
    build: ./backend
    ports:
      - "4003:4000"
    environment:
      - SESSION_SECRET=your-very-strong-secret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
      - frontend